from dataclasses import dataclass
from datetime import datetime

"""
Represents a single telemetry event generated by an industrial machine.
"""

@dataclass
class SensorEvent:
    event_id: str
    timestamp: datetime
    machine_id: int
    temperature: float
    vibration: float
    humidity: float
    pressure: float
    energy_consumption: float
    machine_status: str

